---
name: Docker CI for master branch

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: repository checkout
      uses: actions/checkout@master

    - name: container registry login
      uses: Azure/docker-login@v1
      with:
        login-server: terraformshowoff.azurecr.io
        username: "${{ secrets.ACR_USER }}"
        password: "${{ secrets.ACR_PASS }}"

    - name: build docker image
      run: docker build . -t "terraformshowoff.azurecr.io/showoff:${{ github.run_id }}"

    - name: push docker image
      run: docker push "terraformshowoff.azurecr.io/showoff:${{ github.run_id }}"
