---
name: CI for development branches

on:
  push:
    branches:
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: Azure/docker-login@v1
      with:
        login-server: appdeployregistry.azurecr.io
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASS }}

    - run: docker build . -t appdeployregistry.azurecr.io/showoff:${{ github.sha }}
    - run: docker push appdeployregistry.azurecr.io/showoff:${{ github.sha }}
